### ISSUE TITLE
Session not created

### ISSUE THREAD

**Issue by Bhavikkumarpatel** [WebProcessControl/wpcp2opcua#1]
I am trying to run wpcp2opcua.exe but it is showing session not created. I don't know how to solve this problem.

Could you please help me ?

I attached the snapshot while i run wpcp2opcua.exe.

![capture1](https://user-images.githubusercontent.com/41054577/43356539-a0fdd506-9272-11e8-87d0-ca7807f74c72.JPG)

**Comment by paroga** [comment]
If you only want to use the OPC UA version, I'd recommend you to use the native OPC UA WebSocket bindings instead.
